# Generated by Django 3.0.4 on 2020-03-27 12:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('calories_per_gram', models.FloatField()),
                ('water_per_gram', models.FloatField()),
                ('protein_per_gram', models.FloatField()),
                ('carbs_per_gram', models.FloatField()),
                ('sugar_per_gram', models.FloatField()),
                ('fiber_per_gram', models.FloatField()),
                ('fat_per_gram', models.FloatField()),
                ('vitamin_c_per_gram', models.FloatField()),
                ('potassium_per_gram', models.FloatField()),
                ('average_gram_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('calories', models.FloatField()),
                ('average_weight', models.FloatField()),
                ('servings', models.FloatField()),
                ('description', models.TextField(max_length=2560)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=256), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_units', models.FloatField(blank=True)),
                ('amount_gram', models.FloatField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Recipe')),
            ],
        ),
    ]
